name: AWS Deploy Infrastructure

on:
  push:
    branches:
      - teste-infra-workflow #trocar depois para main (teste-infra para main *ou para a branch default do projeto prefeitura*)

permissions:
  contents: read
  id-token: write

#env:
#  AWS_REGION: us-east-1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.2.4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ vars.AWS_REGION }}

      - name: Verify AWS Credentials
        run: |
          aws sts get-caller-identity

